apiVersion: v1
kind: Service
metadata:
  name: activemq-service
spec:
  type: NodePort
  selector:
    app: activemq
  ports:
    - protocol: TCP
      port: 61616
      targetPort: 61616
      nodePort: 31616