spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/beer-seller
    username: beer-seller
    password: beer-seller
    driverClassName: org.postgresql.Driver
url:
  inventory: http://localhost:8183
  pricing: http://localhost:8184
  beer: http://localhost:8185
