hibernate:
  dialect: org.hibernate.dialect.PostgreSQLDialect
spring:
  flyway:
    enabled: true
    locations: "classpath:db/migrations"
    baseline-on-migrate: true
  datasource:
    url: jdbc:postgresql://localhost:5432/beer-seller
    username: beer-seller
    password: beer-seller
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      use-new-id-generator-mappings: false
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true # Optional, for logging SQL statements
