version: '3.8'

services:
  beer-seller-database:
    image: postgres:15.4
    environment:
      - POSTGRES_DB=beer-seller
      - POSTGRES_USER=beer-seller
      - POSTGRES_PASSWORD=beer-seller
    ports:
      - "5432:5432"
    volumes:
      - beer-seller-data:/var/lib/postgresql/data

  message-broker:
    image: rmohr/activemq
    ports:
      - "61616:61616"
      - "8161:8161"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch
    environment:
      - discovery.type=single-node
      - cluster.name=my_cluster_name
      - ELASTIC_USERNAME=your_username
      - ELASTIC_PASSWORD=your_password
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - es-data:/usr/share/elasticsearch/data

volumes:
  beer-seller-data:
  es-data: