version: '3.1'

services:
  beer-seller-database:
    image: postgres:15.4
    environment:
      - POSTGRES_DB=beer-seller
      - POSTGRES_USER=beer-seller
      - POSTGRES_PASSWORD=beer-seller
    ports:
      - "5432:5432"
    volumes:
      - beer-seller-data:/var/lib/postgresql/data

  message-broker:
    image: rmohr/activemq
    ports:
      - "61616:61616"
      - "8161:8161"

volumes:
  beer-seller-data: